"""
WLAN Signal-Tester - Mehrsprachigkeit (sprachen.py)
Verwaltet Uebersetzungen fuer 8 Sprachen ohne Emojis.
"""

LANGUAGES = [
    ("de", "Deutsch (DE)"),
    ("en", "English (EN)"),
    ("fr", "Français (FR)"),
    ("es", "Español (ES)"),
    ("zh", "中文 (ZH)"),
    ("ru", "Русский (RU)"),
    ("ar", "العربية (AR)"),
    ("fa", "فارسی (FA)"),
]

RTL_LANGUAGES = {"ar", "fa"}

_CURRENT_LANG = "de"

TRANSLATIONS = {
    # Deutsch (Standard)
    "de": {
        "app_title": "WLAN Signal-Tester [ESP32 & Interne WLAN-Karte]",
        "brand": "WIFI SIGNAL ANALYZER",
        "port_lbl": "Schnittstelle:",
        "internal_wifi_card": "[WLAN-Karte] Interne PC Wi-Fi Karte",
        "scan_networks": "Netze scannen",
        "refresh": "Aktualisieren",
        "connect": "Verbinden",
        "disconnect": "Trennen",
        "floorplan_btn": "Wohnungs-Heatmap...",
        "diagnostics_btn": "Netzwerk-Diagnose...",
        "switch_to_diagnostics": "Netzwerk-Diagnose",
        "switch_to_analyzer": "Signal-Analyzer",
        "view_analyzer": "Signal-Analyzer",
        "view_diagnostics": "Netzwerk-Diagnose",
        "view_heatmap": "Signal-Heatmap (Grundriss)",
        "status_connected": "VERBUNDEN",
        "status_disconnected": "GETRENNT",
        "target_cfg_title": "ZIELKONFIGURATION:",
        "ssid_lbl": "SSID:",
        "ssid_placeholder": "SSID auswählen oder eingeben...",
        "bssid_lbl": "BSSID:",
        "bssid_placeholder": "Optional (MAC)",
        "channel_lbl": "Kanal:",
        "rate_lbl": "Rate:",
        "apply_filter": "Filter anwenden",
        "card_target_title": "MESSZIEL & KANAL",
        "card_signal_title": "SIGNALSTÄRKE (RSSI)",
        "card_10s_title": "LETZTE 10 SEKUNDEN",
        "card_mod_title": "MODULATION & PHY-MODUS",
        "card_telem_title": "SYSTEM-TELEMETRIE (60s)",
        "raw_lbl": "Rohwert",
        "channel_fmt": "Kanal: {ch} ({band})",
        "bssid_fmt": "BSSID: {bssid}",
        "plot_title": "ECHTZEIT-SIGNALPEGEL (RSSI / 60 SEKUNDEN)",
        "filter_lbl": "Filter:",
        "filter_medium": "Echtzeit (Empfohlen, adaptiv)",
        "filter_strong": "Gedämpft (Ruhig, Alpha 0.15)",
        "filter_light": "Mittel (Ausgewogen, Alpha 0.40)",
        "filter_off": "Aus (Rohdaten, 100% Direkt)",
        "show_raw": "Rohdaten-Trace anzeigen",
        "show_mean": "Mittelwertlinie",
        "ping_target_lbl": "Ziel-IP / DNS:",
        "plot_y_label": "Signalstärke",
        "plot_x_label": "Vergangene Zeit",
        "alarm_title": "GRENZWERT-ALARM",
        "alarm_active": "Alarm aktiv",
        "threshold_lbl": "Schwelle:",
        "alarm_banner": "WARNUNG: SIGNALSTÄRKE UNTER SCHWELLENWERT",
        "alarm_normal": "SIGNALPEGEL IM NORMALBEREICH (KEIN ALARM)",
        "logger_title": "MESSDATEN-LOGGER (EXCEL / CSV)",
        "start_recording": "Aufzeichnung starten",
        "stop_recording": "Aufzeichnung beenden",
        "export_btn": "Exportieren...",
        "records_count": "{count} Datensätze",
        "sample_rate": "Abtastrate: {rate:.1f} Hz",
        "total_packets": "Pakete gesamt: {count}",
        "fluctuation": "Schwankung: {delta:.1f} dB",
        "min_max_fmt": "Min: {min:+.0f} | Max: {max:+.0f} dBm",
        "stat_overlay": "Min: {min:.1f} | Max: {max:.1f} | Avg: {avg:.1f} dBm",
        "sig_stable": "Signal: Stabil (< 3 dB)",
        "sig_moderate": "Signal: Normale Dynamik (3-8 dB)",
        "sig_jitter": "Signal: Hoher Jitter (> 8 dB)",
        "waiting_data": "Warte auf Signal",
        "qual_critical": "Kritisch / Kein Signal",
        "qual_excellent": "Ausgezeichnet",
        "qual_very_good": "Sehr gut",
        "qual_good": "Gut / Stabil",
        "qual_attenuated": "Dämpfung",
        "qual_weak": "Schwach",
        # Floorplan strings
        "fp_title": "WLAN-Grundriss & Signal-Heatmap [Messreihe]",
        "fp_load": "Grundriss laden (SVG / Bild)...",
        "fp_no_file": "Keine Datei geladen",
        "fp_loaded": "Geladen: {file}",
        "fp_live": "Live-Signal: {val}",
        "fp_points_title": "MESSPUNKTE & WERTE",
        "fp_hint": "Klicke in den Grundriss, um Messpunkte zu setzen. Geh zum Punkt und erfasse den Wert (Leertaste).",
        "fp_col_pt": "Punkt",
        "fp_col_val": "Signal (dBm)",
        "fp_col_status": "Status",
        "fp_capture": "Messwert erfassen (Leertaste)",
        "fp_recompute": "Heatmap berechnen",
        "fp_del_pt": "Punkt löschen",
        "fp_del_all": "Alle löschen",
        "fp_toggle_hm": "Heatmap einblenden",
        "fp_opacity": "Deckkraft:",
        "fp_export_img": "Bild exportieren...",
        "fp_export_csv": "CSV exportieren...",
        "fp_recorded": "Erfasst",
        "fp_open": "Offen",
        "fp_point_name": "Messpunkt {id}",
        "fp_lvl_vweak": "< -80 dBm (Schwach)",
        "fp_lvl_strong": "> -50 dBm (Stark)",
        # Netzwerk-Diagnose
        "diag_title": "WLAN-Diagnose & Netzwerk-Benchmark",
        "diag_subtitle": "Misst Verbindungsaufbau, DHCP, DNS und vergleicht Router- mit Internet-Latenz im Live-Graph.",
        "diag_ssid": "SSID:",
        "diag_ssid_placeholder": "WLAN-Name...",
        "diag_pass": "Passwort:",
        "diag_pass_placeholder": "WPA2/WPA3 (optional)",
        "diag_tester": "Prüfer:",
        "diag_tester_host": "Host-PC (WLAN-Karte)",
        "diag_tester_esp32": "ESP32 (Hardware)",
        "diag_target": "Ping-Ziel:",
        "diag_start": "Diagnose starten",
        "diag_stop": "Diagnose abbrechen",
        "diag_card_dhcp": "VERBINDUNGSAUFBAU & DHCP",
        "diag_card_dns": "DNS-AUFLÖSUNGSZEIT",
        "diag_card_gw": "ROUTER-PING (WLAN)",
        "diag_card_inet": "INTERNET-PING (WAN)",
        "diag_ready": "Bereit zum Test",
        "diag_graph_title": "LIVE-PINGVERLAUF (60 SEKUNDEN)",
        "diag_leg_router": "— Router (WLAN)",
        "diag_leg_internet": "— Internet (WAN)",
        "diag_y_label": "RTT / Latenz",
        "diag_x_label": "Zeit",
        "diag_stats_fmt": "Router: {gw} ms | Internet: {inet} ms | Delta: {delta} ms",
        "diag_status_ready": "Bereit",
        "diag_status_stopped": "Diagnose beendet.",
        "diag_status_done": "Diagnose abgeschlossen. Live-Ping läuft...",
        "diag_opt": "Optimal (< 1.5s)",
        "diag_moderate": "Mäßig",
        "diag_slow": "Langsam",
        "diag_fast": "Schnell",
        "diag_normal": "Normal",
        "diag_delayed": "Verzögert",
        "diag_timeout": "Timeout",
        "diag_error": "Fehler",
        "diag_no_conn": "Keine Verbindung",
    },

    # English
    "en": {
        "app_title": "Wi-Fi Signal Strength Analyzer [ESP32 & Internal Wi-Fi]",
        "brand": "WIFI SIGNAL ANALYZER",
        "port_lbl": "Interface:",
        "internal_wifi_card": "[Wi-Fi Card] Internal PC Wi-Fi Card",
        "scan_networks": "Scan Networks",
        "refresh": "Refresh",
        "connect": "Connect",
        "disconnect": "Disconnect",
        "floorplan_btn": "Floorplan Heatmap...",
        "diagnostics_btn": "Network Diagnostics...",
        "switch_to_diagnostics": "Network Diagnostics",
        "switch_to_analyzer": "Signal Analyzer",
        "view_analyzer": "Signal Analyzer",
        "view_diagnostics": "Network Diagnostics",
        "view_heatmap": "Signal Heatmap (Floorplan)",
        "status_connected": "CONNECTED",
        "status_disconnected": "DISCONNECTED",
        "target_cfg_title": "TARGET CONFIGURATION:",
        "ssid_lbl": "SSID:",
        "ssid_placeholder": "Select or type router SSID...",
        "bssid_lbl": "BSSID:",
        "bssid_placeholder": "Optional (MAC)",
        "channel_lbl": "Channel:",
        "rate_lbl": "Rate:",
        "apply_filter": "Apply Filter",
        "card_target_title": "TARGET & CHANNEL",
        "card_signal_title": "SIGNAL STRENGTH (RSSI)",
        "card_10s_title": "LAST 10 SECONDS",
        "card_mod_title": "MODULATION & PHY MODE",
        "card_telem_title": "SYSTEM TELEMETRY (60s)",
        "raw_lbl": "Raw",
        "channel_fmt": "Channel: {ch} ({band})",
        "bssid_fmt": "BSSID: {bssid}",
        "plot_title": "REAL-TIME SIGNAL LEVEL (RSSI / 60 SECONDS)",
        "filter_lbl": "Filter:",
        "filter_medium": "Medium (Recommended, Alpha 0.20)",
        "filter_strong": "Strong (Damped, Alpha 0.08)",
        "filter_light": "Light (Fast, Alpha 0.45)",
        "filter_off": "Off (Raw Data, Alpha 1.0)",
        "show_raw": "Show raw data trace",
        "show_mean": "Mean Line",
        "ping_target_lbl": "Target IP / DNS:",
        "plot_y_label": "Signal Strength",
        "plot_x_label": "Elapsed Time",
        "alarm_title": "THRESHOLD ALARM",
        "alarm_active": "Alarm active",
        "threshold_lbl": "Threshold:",
        "alarm_banner": "WARNING: SIGNAL STRENGTH BELOW THRESHOLD",
        "alarm_normal": "SIGNAL LEVEL NORMAL (NO ALARM)",
        "logger_title": "DATA LOGGER (EXCEL / CSV)",
        "start_recording": "Start Recording",
        "stop_recording": "Stop Recording",
        "export_btn": "Export...",
        "records_count": "{count} Records",
        "sample_rate": "Sample Rate: {rate:.1f} Hz",
        "total_packets": "Total Packets: {count}",
        "fluctuation": "Fluctuation: {delta:.1f} dB",
        "min_max_fmt": "Min: {min:+.0f} | Max: {max:+.0f} dBm",
        "stat_overlay": "Min: {min:.1f} | Max: {max:.1f} | Avg: {avg:.1f} dBm",
        "sig_stable": "Signal: Stable (< 3 dB)",
        "sig_moderate": "Signal: Normal Dynamics (3-8 dB)",
        "sig_jitter": "Signal: High Jitter (> 8 dB)",
        "waiting_data": "Waiting for Signal",
        "qual_critical": "Critical / No Signal",
        "qual_excellent": "Excellent",
        "qual_very_good": "Very Good",
        "qual_good": "Good / Stable",
        "qual_attenuated": "Attenuated",
        "qual_weak": "Weak",
        "fp_title": "Wi-Fi Floorplan & Signal Heatmap [Survey]",
        "fp_load": "Load Floorplan (SVG / Image)...",
        "fp_no_file": "No file loaded",
        "fp_loaded": "Loaded: {file}",
        "fp_live": "Live Signal: {val}",
        "fp_points_title": "SURVEY POINTS & VALUES",
        "fp_hint": "Click on floorplan to place survey points. Walk to point and capture value (Spacebar).",
        "fp_col_pt": "Point",
        "fp_col_val": "Signal (dBm)",
        "fp_col_status": "Status",
        "fp_capture": "Capture Value (Spacebar)",
        "fp_recompute": "Calculate Heatmap",
        "fp_del_pt": "Delete Point",
        "fp_del_all": "Clear All",
        "fp_toggle_hm": "Show Heatmap",
        "fp_opacity": "Opacity:",
        "fp_export_img": "Export Image...",
        "fp_export_csv": "Export CSV...",
        "fp_recorded": "Captured",
        "fp_open": "Pending",
        "fp_point_name": "Point {id}",
        "fp_lvl_vweak": "< -80 dBm (Weak)",
        "fp_lvl_strong": "> -50 dBm (Strong)",
        # Network Diagnostics
        "diag_title": "Wi-Fi Diagnostics & Network Benchmark",
        "diag_subtitle": "Measures connection, DHCP, DNS and compares router vs. internet latency in live graph.",
        "diag_ssid": "SSID:",
        "diag_ssid_placeholder": "Wi-Fi name...",
        "diag_pass": "Password:",
        "diag_pass_placeholder": "WPA2/WPA3 (optional)",
        "diag_tester": "Tester:",
        "diag_tester_host": "Host PC (Wi-Fi Card)",
        "diag_tester_esp32": "ESP32 (Hardware)",
        "diag_target": "Ping Target:",
        "diag_start": "Start Diagnostics",
        "diag_stop": "Stop Diagnostics",
        "diag_card_dhcp": "CONNECTION & DHCP",
        "diag_card_dns": "DNS RESOLUTION TIME",
        "diag_card_gw": "ROUTER PING (WI-FI)",
        "diag_card_inet": "INTERNET PING (WAN)",
        "diag_ready": "Ready to test",
        "diag_graph_title": "LIVE PING TRACE (60 SECONDS)",
        "diag_leg_router": "— Router (Wi-Fi)",
        "diag_leg_internet": "— Internet (WAN)",
        "diag_y_label": "RTT / Latency",
        "diag_x_label": "Time",
        "diag_stats_fmt": "Router: {gw} ms | Internet: {inet} ms | Delta: {delta} ms",
        "diag_status_ready": "Ready",
        "diag_status_stopped": "Diagnostics stopped.",
        "diag_status_done": "Diagnostics completed. Live ping running...",
        "diag_opt": "Optimal (< 1.5s)",
        "diag_moderate": "Moderate",
        "diag_slow": "Slow",
        "diag_fast": "Fast",
        "diag_normal": "Normal",
        "diag_delayed": "Delayed",
        "diag_timeout": "Timeout",
        "diag_error": "Error",
        "diag_no_conn": "No connection",
    },

    # Français
    "fr": {
        "app_title": "Analyseur Wi-Fi [ESP32 & Carte Wi-Fi Interne]",
        "brand": "WIFI SIGNAL ANALYZER",
        "port_lbl": "Interface :",
        "internal_wifi_card": "[Carte Wi-Fi] Carte Wi-Fi interne du PC",
        "scan_networks": "Scanner réseaux",
        "refresh": "Actualiser",
        "connect": "Connecter",
        "disconnect": "Déconnecter",
        "floorplan_btn": "Carte thermique...",
        "diagnostics_btn": "Diagnostics réseau...",
        "switch_to_diagnostics": "Diagnostic Réseau",
        "switch_to_analyzer": "Analyseur de Signal",
        "view_analyzer": "Analyseur de Signal",
        "view_diagnostics": "Diagnostic Réseau",
        "view_heatmap": "Carte Thermique (Plan)",
        "status_connected": "CONNECTÉ",
        "status_disconnected": "DÉCONNECTÉ",
        "target_cfg_title": "CONFIGURATION CIBLE :",
        "ssid_lbl": "SSID :",
        "ssid_placeholder": "Sélectionner ou saisir le SSID...",
        "bssid_lbl": "BSSID :",
        "bssid_placeholder": "Optionnel (MAC)",
        "channel_lbl": "Canal :",
        "rate_lbl": "Débit :",
        "apply_filter": "Appliquer le filtre",
        "card_target_title": "CIBLE & CANAL",
        "card_signal_title": "PUISSANCE DU SIGNAL (RSSI)",
        "card_10s_title": "10 DERNIÈRES SECONDES",
        "card_mod_title": "MODULATION & MODE PHY",
        "card_telem_title": "TÉLÉMÉTRIE SYSTÈME (60s)",
        "raw_lbl": "Brut",
        "channel_fmt": "Canal : {ch} ({band})",
        "bssid_fmt": "BSSID : {bssid}",
        "plot_title": "NIVEAU DU SIGNAL EN TEMPS RÉEL (RSSI / 60 SECONDES)",
        "filter_lbl": "Filtre :",
        "filter_medium": "Moyen (Recommandé, Alpha 0.20)",
        "filter_strong": "Fort (Atténué, Alpha 0.08)",
        "filter_light": "Léger (Rapide, Alpha 0.45)",
        "filter_off": "Désactivé (Données brutes, Alpha 1.0)",
        "show_raw": "Afficher courbe brute",
        "show_mean": "Ligne moyenne",
        "ping_target_lbl": "IP Cible / DNS :",
        "plot_y_label": "Puissance du Signal",
        "plot_x_label": "Temps écoulé",
        "alarm_title": "ALARME DE SEUIL",
        "alarm_active": "Alarme active",
        "threshold_lbl": "Seuil :",
        "alarm_banner": "ATTENTION : SIGNAL INFÉRIEUR AU SEUIL",
        "alarm_normal": "NIVEAU DU SIGNAL NORMAL (PAS D'ALARME)",
        "logger_title": "ENREGISTREUR (EXCEL / CSV)",
        "start_recording": "Démarrer l'enregistrement",
        "stop_recording": "Arrêter l'enregistrement",
        "export_btn": "Exporter...",
        "records_count": "{count} Enregistrements",
        "sample_rate": "Taux d'échantillonnage : {rate:.1f} Hz",
        "total_packets": "Total paquets : {count}",
        "fluctuation": "Fluctuation : {delta:.1f} dB",
        "min_max_fmt": "Min : {min:+.0f} | Max : {max:+.0f} dBm",
        "stat_overlay": "Min : {min:.1f} | Max : {max:.1f} | Moy : {avg:.1f} dBm",
        "sig_stable": "Signal : Stable (< 3 dB)",
        "sig_moderate": "Signal : Dynamique normale (3-8 dB)",
        "sig_jitter": "Signal : Instable (> 8 dB)",
        "waiting_data": "En attente de signal",
        "qual_critical": "Critique / Aucun signal",
        "qual_excellent": "Excellent",
        "qual_very_good": "Très bon",
        "qual_good": "Bon / Stable",
        "qual_attenuated": "Atténué",
        "qual_weak": "Faible",
        "fp_title": "Plan d'étage et carte thermique Wi-Fi",
        "fp_load": "Charger le plan (SVG / Image)...",
        "fp_no_file": "Aucun fichier chargé",
        "fp_loaded": "Chargé : {file}",
        "fp_live": "Signal direct : {val}",
        "fp_points_title": "POINTS DE MESURE & VALEURS",
        "fp_hint": "Cliquez pour placer des points. Allez au point et capturez la valeur (Espace).",
        "fp_col_pt": "Point",
        "fp_col_val": "Signal (dBm)",
        "fp_col_status": "Statut",
        "fp_capture": "Capturer la valeur (Espace)",
        "fp_recompute": "Calculer la carte thermique",
        "fp_del_pt": "Supprimer le point",
        "fp_del_all": "Tout effacer",
        "fp_toggle_hm": "Afficher carte thermique",
        "fp_opacity": "Opacité :",
        "fp_export_img": "Exporter l'image...",
        "fp_export_csv": "Exporter CSV...",
        "fp_recorded": "Capturé",
        "fp_open": "En attente",
        "fp_point_name": "Point {id}",
        "fp_lvl_vweak": "< -80 dBm (Faible)",
        "fp_lvl_strong": "> -50 dBm (Fort)",
        # Diagnostic Réseau
        "diag_title": "Diagnostic Wi-Fi et benchmark réseau",
        "diag_subtitle": "Mesure la connexion, DHCP, DNS et compare la latence routeur vs Internet en direct.",
        "diag_ssid": "SSID :",
        "diag_ssid_placeholder": "Nom du réseau...",
        "diag_pass": "Mot de passe :",
        "diag_pass_placeholder": "WPA2/WPA3 (optionnel)",
        "diag_tester": "Testeur :",
        "diag_tester_host": "PC hôte (carte Wi-Fi)",
        "diag_tester_esp32": "ESP32 (Matériel)",
        "diag_target": "Cible Ping :",
        "diag_start": "Démarrer diagnostic",
        "diag_stop": "Arrêter diagnostic",
        "diag_card_dhcp": "CONNEXION ET DHCP",
        "diag_card_dns": "TEMPS DE RÉSOLUTION DNS",
        "diag_card_gw": "PING ROUTEUR (WI-FI)",
        "diag_card_inet": "PING INTERNET (WAN)",
        "diag_ready": "Prêt pour le test",
        "diag_graph_title": "SUIVI DU PING EN DIRECT (60 SECONDES)",
        "diag_leg_router": "— Routeur (Wi-Fi)",
        "diag_leg_internet": "— Internet (WAN)",
        "diag_y_label": "RTT / Latence",
        "diag_x_label": "Temps",
        "diag_stats_fmt": "Routeur : {gw} ms | Internet : {inet} ms | Delta : {delta} ms",
        "diag_status_ready": "Prêt",
        "diag_status_stopped": "Diagnostic arrêté.",
        "diag_status_done": "Diagnostic terminé. Ping en direct en cours...",
        "diag_opt": "Optimal (< 1.5s)",
        "diag_moderate": "Modéré",
        "diag_slow": "Lent",
        "diag_fast": "Rapide",
        "diag_normal": "Normal",
        "diag_delayed": "Retardé",
        "diag_timeout": "Délai dépassé",
        "diag_error": "Erreur",
        "diag_no_conn": "Pas de connexion",
    },

    # Español
    "es": {
        "app_title": "Analizador Wi-Fi [ESP32 y Tarjeta Wi-Fi Interna]",
        "brand": "WIFI SIGNAL ANALYZER",
        "port_lbl": "Interfaz:",
        "internal_wifi_card": "[Tarjeta Wi-Fi] Tarjeta Wi-Fi interna de PC",
        "scan_networks": "Escanear redes",
        "refresh": "Actualizar",
        "connect": "Conectar",
        "disconnect": "Desconectar",
        "floorplan_btn": "Mapa de Calor...",
        "diagnostics_btn": "Diagnóstico de red...",
        "switch_to_diagnostics": "Diagnóstico de Red",
        "switch_to_analyzer": "Analizador de Señal",
        "view_analyzer": "Analizador de Señal",
        "view_diagnostics": "Diagnóstico de Red",
        "view_heatmap": "Mapa de Calor (Plano)",
        "status_connected": "CONECTADO",
        "status_disconnected": "DESCONECTADO",
        "target_cfg_title": "CONFIGURACIÓN OBJETIVO:",
        "ssid_lbl": "SSID:",
        "ssid_placeholder": "Seleccionar o escribir SSID...",
        "bssid_lbl": "BSSID:",
        "bssid_placeholder": "Opcional (MAC)",
        "channel_lbl": "Canal:",
        "rate_lbl": "Tasa:",
        "apply_filter": "Aplicar filtro",
        "card_target_title": "OBJETIVO Y CANAL",
        "card_signal_title": "POTENCIA DE SEÑAL (RSSI)",
        "card_10s_title": "ÚLTIMOS 10 SEGUNDOS",
        "card_mod_title": "MODULACIÓN Y MODO PHY",
        "card_telem_title": "TELEMETRÍA DEL SISTEMA (60s)",
        "raw_lbl": "Bruto",
        "channel_fmt": "Canal: {ch} ({band})",
        "bssid_fmt": "BSSID: {bssid}",
        "plot_title": "NIVEL DE SEÑAL EN TIEMPO REAL (RSSI / 60 SEGUNDOS)",
        "filter_lbl": "Filtro:",
        "filter_medium": "Medio (Recomendado, Alfa 0.20)",
        "filter_strong": "Fuerte (Atenuado, Alfa 0.08)",
        "filter_light": "Ligero (Rápido, Alfa 0.45)",
        "filter_off": "Desactivado (Datos brutos, Alfa 1.0)",
        "show_raw": "Mostrar traza de datos brutos",
        "show_mean": "Línea media",
        "ping_target_lbl": "IP Objetivo / DNS:",
        "plot_y_label": "Potencia de Señal",
        "plot_x_label": "Tiempo transcurrido",
        "alarm_title": "ALARMA DE UMBRAL",
        "alarm_active": "Alarma activa",
        "threshold_lbl": "Umbral:",
        "alarm_banner": "ADVERTENCIA: SEÑAL POR DEBAJO DEL UMBRAL",
        "alarm_normal": "NIVEL DE SEÑAL NORMAL (SIN ALARMA)",
        "logger_title": "REGISTRADOR (EXCEL / CSV)",
        "start_recording": "Iniciar grabación",
        "stop_recording": "Detener grabación",
        "export_btn": "Exportar...",
        "records_count": "{count} Registros",
        "sample_rate": "Frecuencia: {rate:.1f} Hz",
        "total_packets": "Paquetes totales: {count}",
        "fluctuation": "Fluctuación: {delta:.1f} dB",
        "min_max_fmt": "Mín: {min:+.0f} | Máx: {max:+.0f} dBm",
        "stat_overlay": "Mín: {min:.1f} | Máx: {max:.1f} | Prom: {avg:.1f} dBm",
        "sig_stable": "Señal: Estable (< 3 dB)",
        "sig_moderate": "Señal: Normal (3-8 dB)",
        "sig_jitter": "Señal: Alto jitter (> 8 dB)",
        "waiting_data": "Esperando señal",
        "qual_critical": "Crítico / Sin señal",
        "qual_excellent": "Excelente",
        "qual_very_good": "Muy bueno",
        "qual_good": "Bueno / Estable",
        "qual_attenuated": "Atenuado",
        "qual_weak": "Débil",
        "fp_title": "Plano de planta y mapa de calor Wi-Fi",
        "fp_load": "Cargar plano (SVG / Imagen)...",
        "fp_no_file": "Ningún archivo cargado",
        "fp_loaded": "Cargado: {file}",
        "fp_live": "Señal en vivo: {val}",
        "fp_points_title": "PUNTOS DE MEDICIÓN Y VALORES",
        "fp_hint": "Haz clic en el plano para colocar puntos. Ve al punto y captura el valor (Espacio).",
        "fp_col_pt": "Punto",
        "fp_col_val": "Señal (dBm)",
        "fp_col_status": "Estado",
        "fp_capture": "Capturar valor (Espacio)",
        "fp_recompute": "Calcular mapa de calor",
        "fp_del_pt": "Eliminar punto",
        "fp_del_all": "Borrar todo",
        "fp_toggle_hm": "Mostrar mapa de calor",
        "fp_opacity": "Opacidad:",
        "fp_export_img": "Exportar imagen...",
        "fp_export_csv": "Exportar CSV...",
        "fp_recorded": "Capturado",
        "fp_open": "Pendiente",
        "fp_point_name": "Punto {id}",
        "fp_lvl_vweak": "< -80 dBm (Débil)",
        "fp_lvl_strong": "> -50 dBm (Fuerte)",
        # Diagnóstico de Red
        "diag_title": "Diagnóstico Wi-Fi y benchmark de red",
        "diag_subtitle": "Mide conexión, DHCP, DNS y compara la latencia router vs Internet en vivo.",
        "diag_ssid": "SSID:",
        "diag_ssid_placeholder": "Nombre de Wi-Fi...",
        "diag_pass": "Contraseña:",
        "diag_pass_placeholder": "WPA2/WPA3 (opcional)",
        "diag_tester": "Probador:",
        "diag_tester_host": "PC host (tarjeta Wi-Fi)",
        "diag_tester_esp32": "ESP32 (Hardware)",
        "diag_target": "Destino Ping:",
        "diag_start": "Iniciar diagnóstico",
        "diag_stop": "Detener diagnóstico",
        "diag_card_dhcp": "CONEXIÓN Y DHCP",
        "diag_card_dns": "TIEMPO DE RESOLUCIÓN DNS",
        "diag_card_gw": "PING ROUTER (WI-FI)",
        "diag_card_inet": "PING INTERNET (WAN)",
        "diag_ready": "Listo para probar",
        "diag_graph_title": "HISTORIAL DE PING EN VIVO (60 SEGUNDOS)",
        "diag_leg_router": "— Router (Wi-Fi)",
        "diag_leg_internet": "— Internet (WAN)",
        "diag_y_label": "RTT / Latencia",
        "diag_x_label": "Tiempo",
        "diag_stats_fmt": "Router: {gw} ms | Internet: {inet} ms | Delta: {delta} ms",
        "diag_status_ready": "Listo",
        "diag_status_stopped": "Diagnóstico detenido.",
        "diag_status_done": "Diagnóstico completado. Ping en vivo activo...",
        "diag_opt": "Óptimo (< 1.5s)",
        "diag_moderate": "Moderado",
        "diag_slow": "Lento",
        "diag_fast": "Rápido",
        "diag_normal": "Normal",
        "diag_delayed": "Demorado",
        "diag_timeout": "Tiempo agotado",
        "diag_error": "Error",
        "diag_no_conn": "Sin conexión",
    },

    # 中文 (Chinese)
    "zh": {
        "app_title": "Wi-Fi 信号强度分析仪 [ESP32 与 内置网卡]",
        "brand": "WIFI SIGNAL ANALYZER",
        "port_lbl": "网络接口:",
        "internal_wifi_card": "[无线网卡] PC 内置 Wi-Fi 网卡",
        "scan_networks": "扫描网络",
        "refresh": "刷新",
        "connect": "连接",
        "disconnect": "断开",
        "floorplan_btn": "户型热力图...",
        "diagnostics_btn": "网络诊断...",
        "switch_to_diagnostics": "网络诊断",
        "switch_to_analyzer": "信号分析仪",
        "view_analyzer": "信号分析仪",
        "view_diagnostics": "网络诊断",
        "view_heatmap": "信号热图 (平面图)",
        "status_connected": "已连接",
        "status_disconnected": "已断开",
        "target_cfg_title": "目标网络配置:",
        "ssid_lbl": "SSID:",
        "ssid_placeholder": "选择或输入目标路由器 SSID...",
        "bssid_lbl": "BSSID:",
        "bssid_placeholder": "可选 (MAC)",
        "channel_lbl": "信道:",
        "rate_lbl": "采样率:",
        "apply_filter": "应用过滤器",
        "card_target_title": "目标与信道",
        "card_signal_title": "信号强度 (RSSI)",
        "card_10s_title": "最近 10 秒统计",
        "card_mod_title": "调制方式与 PHY 模式",
        "card_telem_title": "系统遥测 (60秒)",
        "raw_lbl": "原始值",
        "channel_fmt": "信道: {ch} ({band})",
        "bssid_fmt": "BSSID: {bssid}",
        "plot_title": "实时信号电平 (RSSI / 60 秒)",
        "filter_lbl": "滤波:",
        "filter_medium": "中度 (推荐, Alpha 0.20)",
        "filter_strong": "高度 (平滑, Alpha 0.08)",
        "filter_light": "轻度 (灵敏, Alpha 0.45)",
        "filter_off": "关闭 (原始数据, Alpha 1.0)",
        "show_raw": "显示原始数据曲线",
        "show_mean": "均值线",
        "ping_target_lbl": "目标 IP / DNS:",
        "plot_y_label": "信号强度",
        "plot_x_label": "时间",
        "alarm_title": "阈值警报",
        "alarm_active": "警报已激活",
        "threshold_lbl": "阈值:",
        "alarm_banner": "警告: 信号强度低于设定阈值",
        "alarm_normal": "信号电平正常 (无警报)",
        "logger_title": "数据记录器 (EXCEL / CSV)",
        "start_recording": "开始记录",
        "stop_recording": "停止记录",
        "export_btn": "导出...",
        "records_count": "{count} 条记录",
        "sample_rate": "采样率: {rate:.1f} Hz",
        "total_packets": "数据包总数: {count}",
        "fluctuation": "波动范围: {delta:.1f} dB",
        "min_max_fmt": "最小: {min:+.0f} | 最大: {max:+.0f} dBm",
        "stat_overlay": "最小: {min:.1f} | 最大: {max:.1f} | 平均: {avg:.1f} dBm",
        "sig_stable": "信号: 稳定 (< 3 dB)",
        "sig_moderate": "信号: 正常动态 (3-8 dB)",
        "sig_jitter": "信号: 抖动较高 (> 8 dB)",
        "waiting_data": "等待信号",
        "qual_critical": "极弱 / 无信号",
        "qual_excellent": "极佳",
        "qual_very_good": "非常好",
        "qual_good": "良好 / 稳定",
        "qual_attenuated": "衰减",
        "qual_weak": "较弱",
        "fp_title": "Wi-Fi 户型图与信号热力图 [测量调查]",
        "fp_load": "载入户型图 (SVG / 图片)...",
        "fp_no_file": "未载入文件",
        "fp_loaded": "已载入: {file}",
        "fp_live": "实时信号: {val}",
        "fp_points_title": "测点与数值",
        "fp_hint": "点击户型图添加测点。携带设备到测点并记录信号值（空格键）。",
        "fp_col_pt": "测点",
        "fp_col_val": "信号 (dBm)",
        "fp_col_status": "状态",
        "fp_capture": "采集当前数值 (空格键)",
        "fp_recompute": "生成热力图",
        "fp_del_pt": "删除测点",
        "fp_del_all": "清除全部",
        "fp_toggle_hm": "显示热力图",
        "fp_opacity": "透明度:",
        "fp_export_img": "导出图片...",
        "fp_export_csv": "导出 CSV...",
        "fp_recorded": "已记录",
        "fp_open": "未记录",
        "fp_point_name": "测点 {id}",
        "fp_lvl_vweak": "< -80 dBm (微弱)",
        "fp_lvl_strong": "> -50 dBm (强劲)",
        # 网络诊断
        "diag_title": "Wi-Fi 诊断与网络基准测试",
        "diag_subtitle": "测量连接建立、DHCP、DNS，并在实时图表中比较路由器与互联网延迟。",
        "diag_ssid": "SSID:",
        "diag_ssid_placeholder": "Wi-Fi 名称...",
        "diag_pass": "密码:",
        "diag_pass_placeholder": "WPA2/WPA3 (可选)",
        "diag_tester": "测试端:",
        "diag_tester_host": "主机 PC (Wi-Fi 网卡)",
        "diag_tester_esp32": "ESP32 (硬件)",
        "diag_target": "Ping 目标:",
        "diag_start": "开始诊断",
        "diag_stop": "停止诊断",
        "diag_card_dhcp": "连接建立与 DHCP",
        "diag_card_dns": "DNS 解析时间",
        "diag_card_gw": "路由器 PING (WI-FI)",
        "diag_card_inet": "互联网 PING (WAN)",
        "diag_ready": "准备就绪",
        "diag_graph_title": "实时 PING 趋势图 (60 秒)",
        "diag_leg_router": "— 路由器 (Wi-Fi)",
        "diag_leg_internet": "— 互联网 (WAN)",
        "diag_y_label": "往返时延 / 延迟",
        "diag_x_label": "时间",
        "diag_stats_fmt": "路由器: {gw} ms | 互联网: {inet} ms | 差值: {delta} ms",
        "diag_status_ready": "就绪",
        "diag_status_stopped": "诊断已停止。",
        "diag_status_done": "诊断完成。实时 Ping 运行中...",
        "diag_opt": "极佳 (< 1.5s)",
        "diag_moderate": "中等",
        "diag_slow": "较慢",
        "diag_fast": "快速",
        "diag_normal": "正常",
        "diag_delayed": "延迟",
        "diag_timeout": "超时",
        "diag_error": "错误",
        "diag_no_conn": "无连接",
    },

    # Русский (Russian)
    "ru": {
        "app_title": "Анализатор Wi-Fi [ESP32 и встроенная Wi-Fi карта]",
        "brand": "WIFI SIGNAL ANALYZER",
        "port_lbl": "Интерфейс:",
        "internal_wifi_card": "[Wi-Fi карта] Внутренняя Wi-Fi карта ПК",
        "scan_networks": "Сканировать сети",
        "refresh": "Обновить",
        "connect": "Подключить",
        "disconnect": "Отключить",
        "floorplan_btn": "Тепловая карта...",
        "diagnostics_btn": "Диагностика сети...",
        "switch_to_diagnostics": "Диагностика сети",
        "switch_to_analyzer": "Анализатор сигнала",
        "view_analyzer": "Анализатор сигнала",
        "view_diagnostics": "Диагностика сети",
        "view_heatmap": "Тепловая карта (План)",
        "status_connected": "ПОДКЛЮЧЕНО",
        "status_disconnected": "ОТКЛЮЧЕНО",
        "target_cfg_title": "КОНФИГУРАЦИЯ ЦЕЛИ:",
        "ssid_lbl": "SSID:",
        "ssid_placeholder": "Выберите или введите SSID...",
        "bssid_lbl": "BSSID:",
        "bssid_placeholder": "Опционально (MAC)",
        "channel_lbl": "Канал:",
        "rate_lbl": "Частота:",
        "apply_filter": "Применить фильтр",
        "card_target_title": "ЦЕЛЬ И КАНАЛ",
        "card_signal_title": "УРОВЕНЬ СИГНАЛА (RSSI)",
        "card_10s_title": "ПОСЛЕДНИЕ 10 СЕКУНД",
        "card_mod_title": "МОДУЛЯЦИЯ И РЕЖИМ PHY",
        "card_telem_title": "ТЕЛЕМЕТРИЯ СИСТЕМЫ (60с)",
        "raw_lbl": "Исходное",
        "channel_fmt": "Канал: {ch} ({band})",
        "bssid_fmt": "BSSID: {bssid}",
        "plot_title": "УРОВЕНЬ СИГНАЛА В РЕАЛЬНОМ ВРЕМЕНИ (RSSI / 60 СЕКУНД)",
        "filter_lbl": "Фильтр:",
        "filter_medium": "Средний (Рекомендуется, Alpha 0.20)",
        "filter_strong": "Сильный (Сглаженный, Alpha 0.08)",
        "filter_light": "Лёгкий (Быстрый, Alpha 0.45)",
        "filter_off": "Выкл (Исходные данные, Alpha 1.0)",
        "show_raw": "Показать исходный график",
        "show_mean": "Средняя линия",
        "ping_target_lbl": "Целевой IP / DNS:",
        "plot_y_label": "Уровень сигнала",
        "plot_x_label": "Прошедшее время",
        "alarm_title": "СИГНАЛИЗАЦИЯ ПОРОГА",
        "alarm_active": "Активна",
        "threshold_lbl": "Порог:",
        "alarm_banner": "ВНИМАНИЕ: СИГНАЛ НИЖЕ УСТАНОВЛЕННОГО ПОРОГА",
        "alarm_normal": "УРОВЕНЬ СИГНАЛА В НОРМЕ (НЕТ ТРЕВОГИ)",
        "logger_title": "РЕГИСТРАТОР ДАННЫХ (EXCEL / CSV)",
        "start_recording": "Начать запись",
        "stop_recording": "Остановить запись",
        "export_btn": "Экспорт...",
        "records_count": "{count} Записей",
        "sample_rate": "Частота: {rate:.1f} Гц",
        "total_packets": "Всего пакетов: {count}",
        "fluctuation": "Колебания: {delta:.1f} дБ",
        "min_max_fmt": "Мин: {min:+.0f} | Макс: {max:+.0f} дБм",
        "stat_overlay": "Мин: {min:.1f} | Макс: {max:.1f} | Сред: {avg:.1f} дБм",
        "sig_stable": "Сигнал: Стабильный (< 3 дБ)",
        "sig_moderate": "Сигнал: Нормальный (3-8 дБ)",
        "sig_jitter": "Сигнал: Высокий джиттер (> 8 дБ)",
        "waiting_data": "Ожидание сигнала",
        "qual_critical": "Критический / Нет сигнала",
        "qual_excellent": "Отличный",
        "qual_very_good": "Очень хороший",
        "qual_good": "Хороший / Стабильный",
        "qual_attenuated": "Ослабленный",
        "qual_weak": "Слабый",
        "fp_title": "План помещения и тепловая карта Wi-Fi",
        "fp_load": "Загрузить план (SVG / Изображение)...",
        "fp_no_file": "Файл не выбран",
        "fp_loaded": "Загружено: {file}",
        "fp_live": "Текущий сигнал: {val}",
        "fp_points_title": "ТОЧКИ ИЗМЕРЕНИЙ И ДАННЫЕ",
        "fp_hint": "Кликните на плане для добавления точек. Перейдите к точке и сохраните значение (Пробел).",
        "fp_col_pt": "Точка",
        "fp_col_val": "Сигнал (дБм)",
        "fp_col_status": "Статус",
        "fp_capture": "Зафиксировать значение (Пробел)",
        "fp_recompute": "Рассчитать тепловую карту",
        "fp_del_pt": "Удалить точку",
        "fp_del_all": "Очистить всё",
        "fp_toggle_hm": "Отображать карту",
        "fp_opacity": "Прозрачность:",
        "fp_export_img": "Экспорт изображения...",
        "fp_export_csv": "Экспорт в CSV...",
        "fp_recorded": "Записано",
        "fp_open": "Ожидает",
        "fp_point_name": "Точка {id}",
        "fp_lvl_vweak": "< -80 дБм (Слабый)",
        "fp_lvl_strong": "> -50 дБм (Сильный)",
        # Сетевая диагностика
        "diag_title": "Wi-Fi диагностика и сетевой бенчмарк",
        "diag_subtitle": "Измеряет подключение, DHCP, DNS и сравнивает задержку до роутера и интернета.",
        "diag_ssid": "SSID:",
        "diag_ssid_placeholder": "Имя сети...",
        "diag_pass": "Пароль:",
        "diag_pass_placeholder": "WPA2/WPA3 (необязательно)",
        "diag_tester": "Тестер:",
        "diag_tester_host": "ПК (Wi-Fi адаптер)",
        "diag_tester_esp32": "ESP32 (Аппаратный)",
        "diag_target": "Цель Ping:",
        "diag_start": "Запустить тест",
        "diag_stop": "Остановить",
        "diag_card_dhcp": "ПОДКЛЮЧЕНИЕ И DHCP",
        "diag_card_dns": "ВРЕМЯ ОТВЕТА DNS",
        "diag_card_gw": "ПИНГ ДО РОУТЕРА (WI-FI)",
        "diag_card_inet": "ПИНГ ИНТЕРНЕТА (WAN)",
        "diag_ready": "Готов к тесту",
        "diag_graph_title": "ГРАФИК ПИНГА (60 СЕК)",
        "diag_leg_router": "— Роутер (Wi-Fi)",
        "diag_leg_internet": "— Интернет (WAN)",
        "diag_y_label": "RTT / Задержка",
        "diag_x_label": "Время",
        "diag_stats_fmt": "Роутер: {gw} мс | Интернет: {inet} мс | Дельта: {delta} мс",
        "diag_status_ready": "Готов",
        "diag_status_stopped": "Диагностика остановлена.",
        "diag_status_done": "Диагностика завершена. Пинг активен...",
        "diag_opt": "Отлично (< 1.5s)",
        "diag_moderate": "Умеренно",
        "diag_slow": "Медленно",
        "diag_fast": "Быстро",
        "diag_normal": "Норма",
        "diag_delayed": "Задержка",
        "diag_timeout": "Таймаут",
        "diag_error": "Ошибка",
        "diag_no_conn": "Нет связи",
    },

    # العربية (Arabic - RTL)
    "ar": {
        "app_title": "محلل Wi-Fi [ESP32 وبطاقة Wi-Fi الداخلية]",
        "brand": "WIFI SIGNAL ANALYZER",
        "port_lbl": "الواجهة:",
        "internal_wifi_card": "[بطاقة Wi-Fi] بطاقة Wi-Fi الداخلية للكمبيوتر",
        "scan_networks": "مسح الشبكات",
        "refresh": "تحديث",
        "connect": "اتصال",
        "disconnect": "قطع الاتصال",
        "floorplan_btn": "الخريطة الحرارية...",
        "diagnostics_btn": "تشخيص الشبكة...",
        "switch_to_diagnostics": "تشخيص الشبكة",
        "switch_to_analyzer": "محلل الإشارة",
        "view_analyzer": "محلل الإشارة",
        "view_diagnostics": "تشخيص الشبكة",
        "view_heatmap": "الخريطة الحرارية (المخطط)",
        "status_connected": "متصل",
        "status_disconnected": "غير متصل",
        "target_cfg_title": "تكوين الشبكة المستهدفة:",
        "ssid_lbl": "SSID:",
        "ssid_placeholder": "اختر أو اكتب اسم الشبكة...",
        "bssid_lbl": "BSSID:",
        "bssid_placeholder": "اختياري (MAC)",
        "channel_lbl": "القناة:",
        "rate_lbl": "المعدل:",
        "apply_filter": "تطبيق التصفية",
        "card_target_title": "الهدف والقناة",
        "card_signal_title": "قوة الإشارة (RSSI)",
        "card_10s_title": "آخر 10 ثوانٍ",
        "card_mod_title": "التعديل ونمط PHY",
        "card_telem_title": "قياسات النظام (60 ثانية)",
        "raw_lbl": "القيمة الأولية",
        "channel_fmt": "القناة: {ch} ({band})",
        "bssid_fmt": "BSSID: {bssid}",
        "plot_title": "مستوى الإشارة في الوقت الفعلي (RSSI / 60 ثانية)",
        "filter_lbl": "التصفية:",
        "filter_medium": "متوسط (موصى به، Alpha 0.20)",
        "filter_strong": "قوي (مخمد، Alpha 0.08)",
        "filter_light": "خفيف (سريع، Alpha 0.45)",
        "filter_off": "معطل (بيانات أولية، Alpha 1.0)",
        "show_raw": "إظهار مسار البيانات الأولية",
        "show_mean": "خط المتوسط",
        "ping_target_lbl": "الهدف IP / DNS:",
        "plot_y_label": "قوة الإشارة",
        "plot_x_label": "الوقت المنقضي",
        "alarm_title": "إنذار الحد الأدنى",
        "alarm_active": "الإنذار مفعل",
        "threshold_lbl": "الحد الأدنى:",
        "alarm_banner": "تحذير: قوة الإشارة أقل من الحد الأدنى المحدد",
        "alarm_normal": "مستوى الإشارة طبيعي (لا يوجد إنذار)",
        "logger_title": "مسجل البيانات (EXCEL / CSV)",
        "start_recording": "بدء التسجيل",
        "stop_recording": "إيقاف التسجيل",
        "export_btn": "تصدير...",
        "records_count": "{count} سجلات",
        "sample_rate": "معدل العينات: {rate:.1f} هرتز",
        "total_packets": "إجمالي الحزم: {count}",
        "fluctuation": "التذبذب: {delta:.1f} dB",
        "min_max_fmt": "الأدنى: {min:+.0f} | الأقصى: {max:+.0f} dBm",
        "stat_overlay": "الأدنى: {min:.1f} | الأقصى: {max:.1f} | المتوسط: {avg:.1f} dBm",
        "sig_stable": "الإشارة: مستقرة (< 3 dB)",
        "sig_moderate": "الإشارة: تذبذب طبيعي (3-8 dB)",
        "sig_jitter": "الإشارة: تذبذب مرتفع (> 8 dB)",
        "waiting_data": "في انتظار الإشارة",
        "qual_critical": "حرج / لا توجد إشارة",
        "qual_excellent": "ممتاز",
        "qual_very_good": "جيد جداً",
        "qual_good": "جيد / مستقر",
        "qual_attenuated": "مخمد",
        "qual_weak": "ضعيف",
        "fp_title": "مخطط المبنى والخريطة الحرارية لإشارة Wi-Fi",
        "fp_load": "تحميل المخطط (SVG / صورة)...",
        "fp_no_file": "لم يتم تحميل أي ملف",
        "fp_loaded": "تم تحميل: {file}",
        "fp_live": "الإشارة المباشرة: {val}",
        "fp_points_title": "نقاط القياس والقيم",
        "fp_hint": "انقر على المخطط لوضع نقاط القياس. توجه للنقطة وسجل القيمة (مسافة).",
        "fp_col_pt": "النقطة",
        "fp_col_val": "الإشارة (dBm)",
        "fp_col_status": "الحالة",
        "fp_capture": "تسجيل القيمة (مسافة)",
        "fp_recompute": "حساب الخريطة الحرارية",
        "fp_del_pt": "حذف النقطة",
        "fp_del_all": "حذف الكل",
        "fp_toggle_hm": "عرض الخريطة الحرارية",
        "fp_opacity": "الشفافية:",
        "fp_export_img": "تصدير صورة...",
        "fp_export_csv": "تصدير CSV...",
        "fp_recorded": "تم التسجيل",
        "fp_open": "مفتوح",
        "fp_point_name": "نقطة قياس {id}",
        "fp_lvl_vweak": "< -80 dBm (ضعيف)",
        "fp_lvl_strong": "> -50 dBm (قوي)",
        # تشخيص الشبكة
        "diag_title": "تشخيص Wi-Fi واختبار أداء الشبكة",
        "diag_subtitle": "يقيس الاتصال و DHCP و DNS ويقارن زمن انتقال الموجه بالإنترنت مباشرة.",
        "diag_ssid": "SSID:",
        "diag_ssid_placeholder": "اسم الشبكة...",
        "diag_pass": "كلمة المرور:",
        "diag_pass_placeholder": "WPA2/WPA3 (اختياري)",
        "diag_tester": "الفاحص:",
        "diag_tester_host": "الكمبيوتر (بطاقة Wi-Fi)",
        "diag_tester_esp32": "ESP32 (عتاد)",
        "diag_target": "هدف Ping:",
        "diag_start": "بدء التشخيص",
        "diag_stop": "إلغاء التشخيص",
        "diag_card_dhcp": "إنشاء الاتصال و DHCP",
        "diag_card_dns": "زمن حل أسماء DNS",
        "diag_card_gw": "استجابة الموجه (WI-FI)",
        "diag_card_inet": "استجابة الإنترنت (WAN)",
        "diag_ready": "جاهز للاختبار",
        "diag_graph_title": "مسار الاستجابة الحي (60 ثانية)",
        "diag_leg_router": "— الموجه (Wi-Fi)",
        "diag_leg_internet": "— الإنترنت (WAN)",
        "diag_y_label": "زمن الاستجابة / التأخير",
        "diag_x_label": "الوقت",
        "diag_stats_fmt": "الموجه: {gw} ms | الإنترنت: {inet} ms | الفارق: {delta} ms",
        "diag_status_ready": "جاهز",
        "diag_status_stopped": "تم إيقاف التشخيص.",
        "diag_status_done": "اكتمل التشخيص. الفحص الحي يعمل...",
        "diag_opt": "ممتاز (< 1.5s)",
        "diag_moderate": "متوسط",
        "diag_slow": "بطيء",
        "diag_fast": "سريع",
        "diag_normal": "طبيعي",
        "diag_delayed": "متأخر",
        "diag_timeout": "انتهاء المهلة",
        "diag_error": "خطأ",
        "diag_no_conn": "لا يوجد اتصال",
    },

    # فارسی (Persian / Farsi - RTL)
    "fa": {
        "app_title": "تحلیل‌گر وای‌فای [ESP32 و کارت وای‌فای داخلی]",
        "brand": "WIFI SIGNAL ANALYZER",
        "port_lbl": "رابط ارتباطی:",
        "internal_wifi_card": "[کارت وای‌فای] کارت وای‌فای داخلی رایانه",
        "scan_networks": "اسکن شبکه‌ها",
        "refresh": "بروزرسانی",
        "connect": "اتصال",
        "disconnect": "قطع اتصال",
        "floorplan_btn": "نقشه حرارتی...",
        "diagnostics_btn": "عیب‌یابی شبکه...",
        "switch_to_diagnostics": "عیب‌یابی شبکه",
        "switch_to_analyzer": "تحلیل‌گر سیگنال",
        "view_analyzer": "آنالایزر سیگنال",
        "view_diagnostics": "تشخیص شبکه",
        "view_heatmap": "نقشه حرارتی (پلان)",
        "status_connected": "متصل",
        "status_disconnected": "قطع",
        "target_cfg_title": "پیکربندی شبکه هدف:",
        "ssid_lbl": "SSID:",
        "ssid_placeholder": "انتخاب یا تایپ نام شبکه...",
        "bssid_lbl": "BSSID:",
        "bssid_placeholder": "اختیاری (MAC)",
        "channel_lbl": "کانال:",
        "rate_lbl": "نرخ:",
        "apply_filter": "اعمال فیلتر",
        "card_target_title": "هدف و کانال",
        "card_signal_title": "قدرت سیگنال (RSSI)",
        "card_10s_title": "۱۰ ثانیه گذشته",
        "card_mod_title": "مدولاسیون و حالت PHY",
        "card_telem_title": "تله‌متری سیستم (۶۰ ثانیه)",
        "raw_lbl": "داده خام",
        "channel_fmt": "کانال: {ch} ({band})",
        "bssid_fmt": "BSSID: {bssid}",
        "plot_title": "سطح لحظه‌ای سیگنال (RSSI / ۶۰ ثانیه)",
        "filter_lbl": "فیلتر:",
        "filter_medium": "متوسط (پیشنهادی، Alpha 0.20)",
        "filter_strong": "قوی (صاف‌شده، Alpha 0.08)",
        "filter_light": "ملایم (سریع، Alpha 0.45)",
        "filter_off": "خاموش (داده‌های خام، Alpha 1.0)",
        "show_raw": "نمایش منحنی داده‌های خام",
        "show_mean": "خط میانگین",
        "ping_target_lbl": "آی‌پی هدف / DNS:",
        "plot_y_label": "قدرت سیگنال",
        "plot_x_label": "زمان سپری‌شده",
        "alarm_title": "هشدار آستانه",
        "alarm_active": "هشدار فعال",
        "threshold_lbl": "حد آستانه:",
        "alarm_banner": "هشدار: قدرت سیگنال کمتر از حد آستانه است",
        "alarm_normal": "سطح سیگنال عادی است (بدون هشدار)",
        "logger_title": "ثبت‌کننده داده‌ها (EXCEL / CSV)",
        "start_recording": "شروع ضبط",
        "stop_recording": "توقف ضبط",
        "export_btn": "خروجی...",
        "records_count": "{count} رکورد",
        "sample_rate": "نرخ نمونه‌برداری: {rate:.1f} هرتز",
        "total_packets": "کل بسته‌ها: {count}",
        "fluctuation": "میزان نوسان: {delta:.1f} dB",
        "min_max_fmt": "حداقل: {min:+.0f} | حداکثر: {max:+.0f} dBm",
        "stat_overlay": "حداقل: {min:.1f} | حداکثر: {max:.1f} | میانگین: {avg:.1f} dBm",
        "sig_stable": "سیگنال: پایدار (< 3 dB)",
        "sig_moderate": "سیگنال: نوسان معمولی (3-8 dB)",
        "sig_jitter": "سیگنال: ناپایدار (> 8 dB)",
        "waiting_data": "در انتظار سیگنال",
        "qual_critical": "بحرانی / بدون سیگنال",
        "qual_excellent": "عالی",
        "qual_very_good": "بسیار خوب",
        "qual_good": "خوب / پایدار",
        "qual_attenuated": "تضعیف‌شده",
        "qual_weak": "ضعیف",
        "fp_title": "نقشه ساختمان و نقشه حرارتی سیگنال وای‌فای",
        "fp_load": "بارگذاری نقشه (SVG / تصویر)...",
        "fp_no_file": "فایلی انتخاب نشده است",
        "fp_loaded": "بارگذاری شد: {file}",
        "fp_live": "سیگنال زنده: {val}",
        "fp_points_title": "نقاط اندازه‌گیری و مقادیر",
        "fp_hint": "روی نقشه کلیک کنید تا نقاط اندازه‌گیری تعیین شوند. سپس به آن نقطه رفته و مقدار را ثبت کنید (Space).",
        "fp_col_pt": "نقطه",
        "fp_col_val": "سیگنال (dBm)",
        "fp_col_status": "وضعیت",
        "fp_capture": "ثبت مقدار (کلید Space)",
        "fp_recompute": "محاسبه نقشه حرارتی",
        "fp_del_pt": "حذف نقطه",
        "fp_del_all": "حذف همه",
        "fp_toggle_hm": "نمایش نقشه حرارتی",
        "fp_opacity": "میزان وضوح:",
        "fp_export_img": "خروجی تصویر...",
        "fp_export_csv": "خروجی CSV...",
        "fp_recorded": "ثبت شد",
        "fp_open": "در انتظار",
        "fp_point_name": "نقطه اندازه‌گیری {id}",
        "fp_lvl_vweak": "< -80 dBm (ضعیف)",
        "fp_lvl_strong": "> -50 dBm (قوی)",
        # عیب‌یابی شبکه
        "diag_title": "عیب‌یابی Wi-Fi و بنچمارک شبکه",
        "diag_subtitle": "زمان اتصال، DHCP، DNS و تأخیر روتر در مقایسه با اینترنت را زنده نشان می‌دهد.",
        "diag_ssid": "نام شبکه:",
        "diag_ssid_placeholder": "نام شبکه...",
        "diag_pass": "رمز عبور:",
        "diag_pass_placeholder": "WPA2/WPA3 (اختیاری)",
        "diag_tester": "آزمایش‌کننده:",
        "diag_tester_host": "کامپیوتر میزبان (کارت وای‌فای)",
        "diag_tester_esp32": "سخت‌افزار ESP32",
        "diag_target": "مقصد پینگ:",
        "diag_start": "شروع عیب‌یابی",
        "diag_stop": "توقف عیب‌یابی",
        "diag_card_dhcp": "برقراری ارتباط و DHCP",
        "diag_card_dns": "زمان پاسخگویی DNS",
        "diag_card_gw": "پینگ روتر (WI-FI)",
        "diag_card_inet": "پینگ اینترنت (WAN)",
        "diag_ready": "آماده برای تست",
        "diag_graph_title": "نمودار زنده پینگ (۶۰ ثانیه)",
        "diag_leg_router": "— روتر (Wi-Fi)",
        "diag_leg_internet": "— اینترنت (WAN)",
        "diag_y_label": "تاخیر رفت و برگشت (RTT)",
        "diag_x_label": "زمان",
        "diag_stats_fmt": "روتر: {gw} ms | اینترنت: {inet} ms | اختلاف: {delta} ms",
        "diag_status_ready": "آماده",
        "diag_status_stopped": "عیب‌یابی متوقف شد.",
        "diag_status_done": "عیب‌یابی به پایان رسید. پینگ زنده فعال است...",
        "diag_opt": "عالی (< 1.5s)",
        "diag_moderate": "متوسط",
        "diag_slow": "کند",
        "diag_fast": "سریع",
        "diag_normal": "عادی",
        "diag_delayed": "با تاخیر",
        "diag_timeout": "پایان زمان",
        "diag_error": "خطا",
        "diag_no_conn": "بدون اتصال",
    }
}


def get_current_language() -> str:
    global _CURRENT_LANG
    return _CURRENT_LANG


def set_language(lang_code: str):
    global _CURRENT_LANG
    if lang_code in TRANSLATIONS:
        _CURRENT_LANG = lang_code


def is_rtl() -> bool:
    return _CURRENT_LANG in RTL_LANGUAGES


def tr(key: str, **kwargs) -> str:
    """
    Gibt die Übersetzung für einen Schlüssel in der aktuellen Sprache zurück.
    """
    lang_dict = TRANSLATIONS.get(_CURRENT_LANG, TRANSLATIONS["de"])
    val = lang_dict.get(key)
    if val is None:
        val = TRANSLATIONS["de"].get(key, TRANSLATIONS["en"].get(key, key))
    if kwargs:
        try:
            return val.format(**kwargs)
        except Exception:
            return val
    return val


# Deutsche Funktionsnamen fuer einfache Lesbarkeit
text = tr
setze_sprache = set_language
aktuelle_sprache = get_current_language
ist_rechts_nach_links = is_rtl
SPRACHEN = LANGUAGES
